sched/pelt: Remove to function call
error: too many arguments to function call, expected 2, have 3
  416 |                 ___update_load_avg(&rq->avg_thermal, 1, 1);